"""changed users

Revision ID: 9ad01217076f
Revises: d59a3f770c3c
Create Date: 2025-04-05 19:08:16.579488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ad01217076f"
down_revision: Union[str, None] = "d59a3f770c3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "advertisements", "category_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column("users", sa.Column("email", sa.String(length=100), nullable=False))
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=300), nullable=False)
    )
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "email")
    op.alter_column(
        "advertisements", "category_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
