"""changed users

Revision ID: fe6a6a48c4fe
Revises: 9ad01217076f
Create Date: 2025-04-05 20:04:54.613681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6a6a48c4fe'
down_revision: Union[str, None] = '9ad01217076f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'advertisements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.drop_column('advertisements', 'user_id')
    # ### end Alembic commands ###
